import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import {AppLayout} from '../src/components/layout/AppLayout';
import Proxy from '../src/pages/Proxy';
import {RuntimeBridge} from '../src/lib/runtime';
import {OptionalProtocolRefresh} from '../src/components/OptionalProtocolRefresh';
import {useSession} from '../src/store/session';
import {usePermissions} from '../src/store/permissions';
import {applyThemeOnBoot} from '../src/store/theme';
import {availableApplicationTypes} from '../src/constants/applicationTypes';
import {isSQLProtocol} from '../src/pages/WebData/protocol';
import {sqlQualifiedName,sqlQuoteIdent} from '../src/pages/WebData/objectCommands';
import '../src/styles/index.css';
if(!import.meta.env.DEV)throw Error('Development fixture only');
applyThemeOnBoot();
useSession.getState().setToken('dameng-fixture');
void useSession.getState().setInitialState({currentUser:{id:1,name:'Fixture',role:'admin'} as API.CurrentUser});
usePermissions.setState({owner:'dameng-fixture',loaded:true,grants:{}});
Object.assign(window,{damengChecks:{availableApplicationTypes,isSQLProtocol,sqlQualifiedName,sqlQuoteIdent}});
const protocol=new URLSearchParams(location.search).get('protocol')||'dameng';
createRoot(document.getElementById('root')!).render(<MemoryRouter initialEntries={['/proxy?category=database&access_type=web'+protocol]}><RuntimeBridge/><OptionalProtocolRefresh/><Routes><Route element={<AppLayout/>}><Route path="/proxy" element={<Proxy/>}/></Route></Routes></MemoryRouter>);
