import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import Settings from '../src/pages/Settings';
import {RuntimeBridge} from '../src/lib/runtime';
import {applyThemeOnBoot} from '../src/store/theme';
import {usePermissions} from '../src/store/permissions';
import {useSession} from '../src/store/session';
import '../src/styles/index.css';
if(!import.meta.env.DEV)throw Error('Development fixture only');
applyThemeOnBoot();
usePermissions.setState({owner:useSession.getState().token,loaded:true,grants:{'settings.global.read':true,'settings.global.update':true}});
createRoot(document.getElementById('root')!).render(<MemoryRouter><RuntimeBridge/><main style={{padding:24}}><Settings/></main></MemoryRouter>);
