import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import ProxyPage from '../src/pages/Proxy';
import {RuntimeBridge} from '../src/lib/runtime';
import {applyThemeOnBoot} from '../src/store/theme';
import '../src/styles/index.css';
if(!import.meta.env.DEV)throw Error('Development fixture only');
applyThemeOnBoot();
createRoot(document.getElementById('root')!).render(<MemoryRouter initialEntries={['/proxy?category=web&access_type=http']}><RuntimeBridge/><main style={{padding:20}}><ProxyPage/></main></MemoryRouter>);
