import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import Connector from '../src/pages/Connector';
import Application from '../src/pages/App';
import {RuntimeBridge} from '../src/lib/runtime';
import {applyThemeOnBoot} from '../src/store/theme';
import '../src/styles/index.css';
if (!import.meta.env.DEV) throw Error('Development fixture only');
applyThemeOnBoot();
createRoot(document.getElementById('root')!).render(<MemoryRouter><RuntimeBridge/><main style={{padding:20}}>{location.search.includes('application')?<Application/>:<Connector/>}</main></MemoryRouter>);
