import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import WebSMB from '../src/pages/WebSMB';
import {usePermissions} from '../src/store/permissions';
import {useSession} from '../src/store/session';
import {applyThemeOnBoot} from '../src/store/theme';
import '../src/styles/index.css';
if(!import.meta.env.DEV)throw Error('Development fixture only');
applyThemeOnBoot();
usePermissions.setState({owner:useSession.getState().token,loaded:true,grants:{'webssh.files.read':true}});
createRoot(document.getElementById('root')!).render(<React.StrictMode><MemoryRouter initialEntries={['/websmb/1/connections/7']}><main style={{padding:24}}><Routes><Route path="/websmb/:proxyId/connections/:credentialId/*" element={<WebSMB/>}/></Routes></main></MemoryRouter></React.StrictMode>);
