import {agentKinds,agentLabel} from './providers';
import {useEffect,useRef,useState} from 'react';
import {Button,Field,Input,Modal,Notice,Select} from '@/components/ui';
import {useI18n} from '@/i18n';
import {DirectoryBrowser} from './DirectoryBrowser';
import {agentApplications,saveAgentApplication,edgeAgent,saveAgentAccess,type AgentApplication,type AgentAccess,type AgentConnector,type Installation} from '@/services/edgeAgent';

export default function AccessForm({entry,application,defaultKind,connectors,onClose,onSaved}:{entry?:AgentAccess;application?:AgentApplication;defaultKind?:string;connectors:AgentConnector[];onClose:()=>void;onSaved:()=>void}){
  const initialKind=entry?.kind||application?.kind||defaultKind||'codex';
  const {tr}=useI18n();const [kind,setKind]=useState(initialKind);const [name,setName]=useState(entry?.name||`Access-${crypto.randomUUID().slice(0,8)}`),[edge,setEdge]=useState(String(entry?.edge_id||application?.edge_id||connectors.find(c=>c.online)?.id||'')),[project,setProject]=useState(entry?.project||''),[installation,setInstallation]=useState(entry?.installation_id||'');
  const [items,setItems]=useState<Installation[]>([]),[pending,setPending]=useState(false),[error,setError]=useState(''),[discovered,setDiscovered]=useState(false);
  const [source,setSource]=useState('existing'),[applicationID,setApplicationID]=useState(entry?.application_id||application?.id||''),[apps,setApps]=useState<AgentApplication[]>([]),[appsLoading,setAppsLoading]=useState(false),[appName,setAppName]=useState(agentLabel(initialKind));
  useEffect(()=>{if(!edge)return;const abort=new AbortController();setAppsLoading(true);setApps([]);setError('');void (async()=>{try{let page=1,total=0;const rows:AgentApplication[]=[];do{const result=await agentApplications(page++,Number(edge),abort.signal);rows.push(...result.items);total=result.total;if(!result.items.length)break;}while(rows.length<total);if(!abort.signal.aborted)setApps(rows);}catch{if(!abort.signal.aborted)setError(tr('无法加载应用，请重新选择连接器重试。','Cannot load applications. Select the connector again to retry.'));}finally{if(!abort.signal.aborted)setAppsLoading(false);}})();return()=>abort.abort();},[edge]);
  const filteredApps=apps.filter(a=>a.kind===kind);
  const chosen=filteredApps.find(a=>a.id===applicationID)||(application?.id===applicationID&&application.edge_id===Number(edge)&&application.kind===kind?application:undefined);
  const [browsing,setBrowsing]=useState(false);
  const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  async function discover(){setPending(true);setError('');try{
    const result=await edgeAgent(Number(edge),'discover');if(!alive.current)return;
    if(result.status!=='ok'){setError(result.status==='unsupported_user'?tr('请使用普通用户运行的 macOS 或 Linux 连接器。','Use a macOS or Linux connector running as a non-root user.'):tr('无法发现 Agent，请检查连接器及其版本。','Cannot discover Agents. Check the connector and its version.'));return;}
    const found=(result.installations||[]).filter(i=>i.kind===kind);setDiscovered(true);setItems(found);setInstallation(found.find(i=>i.id===installation)?.id||found[0]?.id||'');if(!project)setProject(result.default_project||'');
  }catch{if(alive.current)setError(tr('发现失败，请重试。','Discovery failed. Try again.'));}finally{if(alive.current)setPending(false);}}
  async function save(){setPending(true);setError('');try{let app=chosen;if(source==='new'){app=await saveAgentApplication({name:appName.trim(),kind,edge_id:Number(edge),installation_id:installation});setApplicationID(app.id);setApps(rows=>[...rows.filter(a=>a.id!==app!.id),app!]);setSource('existing');}if(!app)throw new Error('missing application');await saveAgentAccess({application_id:app.id,name:name.trim(),kind:app.kind,edge_id:app.edge_id,installation_id:app.installation_id,project:project.trim()},entry?.id);if(alive.current)onSaved();}catch{if(alive.current)setError(tr('保存失败，请检查配置和连接器权限。','Could not save. Check the configuration and connector permissions.'));}finally{if(alive.current)setPending(false);}}
  return <><Modal open={!browsing} title={entry?tr('编辑访问','Edit access'):tr('新建访问','Create access')} onClose={()=>{if(!pending)onClose();}} footer={<><Button disabled={pending} onClick={onClose}>{tr('取消','Cancel')}</Button><Button variant="primary" loading={pending} disabled={pending||appsLoading||!name.trim()||!edge||(source==='existing'?!chosen:!installation||!appName.trim())||!project.trim()} onClick={()=>void save()}>{entry?tr('保存','Save'):tr('创建访问','Create access')}</Button></>}>
    <div className="edge-agent-form">
      <div className="edge-agent-fields"><Field label={tr('访问名称','Access name')} required><Input value={name} maxLength={120} disabled={pending} onChange={e=>setName(e.target.value)}/></Field><Field label={tr('访问类型', 'Access type')}><Select value={kind} disabled={pending} onChange={e=>{setKind(e.target.value);setApplicationID('');setInstallation('');setItems([]);setDiscovered(false);setAppName(agentLabel(e.target.value));setError('');}}>{agentKinds.map(k=><option key={k.value} value={k.value}>{k.label}</option>)}</Select></Field></div>
      <Field label={tr('连接器','Connector')} required><Select value={edge} disabled={pending} onChange={e=>{setEdge(e.target.value);setApplicationID('');setInstallation('');setItems([]);setProject('');setDiscovered(false);setError('');}}><option value="">{tr('选择连接器','Choose connector')}</option>{connectors.map(c=><option key={c.id} value={c.id}>{c.name}{c.device?` · ${c.device}`:''}{c.online?'':tr(' · 离线',' · Offline')}</option>)}</Select></Field>
      <Field label={tr('应用来源','Application source')}><Select value={source} disabled={pending} onChange={e=>setSource(e.target.value)}><option value="existing">{tr('已有应用','Existing application')}</option><option value="new">{tr('新建应用','New application')}</option></Select></Field>
      {source==='existing'?<Field label={tr('应用','Application')} required><Select value={applicationID} disabled={pending||appsLoading} onChange={e=>setApplicationID(e.target.value)}><option value="">{appsLoading?tr('正在加载…','Loading…'):tr('选择应用','Choose application')}</option>{filteredApps.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select>{!appsLoading&&!filteredApps.length&&<Notice>{tr('暂无已登记的 Agent 应用，请选择新建应用。','No registered Agent applications. Choose New application.')}</Notice>}</Field>:<><Field label={tr('应用名称','Application name')} required><Input value={appName} maxLength={120} disabled={pending} onChange={e=>setAppName(e.target.value)}/></Field><div className="edge-agent-discover"><Button loading={pending} disabled={pending||!connectors.find(c=>String(c.id)===edge)?.online} onClick={()=>void discover()}>{tr('发现已安装的 Agent','Discover installed Agents')}</Button><span>{tr('不会安装软件或更改 Agent 配置。','Does not install software or change Agent configuration.')}</span></div>
      {discovered&&!items.length&&<Notice>{tr('没有找到此运行用户下的 Agent。','No Agent installation found for this OS user.')}</Notice>}
      {(items.length>0||installation)&&<Field label={tr('Agent 安装','Agent installation')} required><Select value={installation} disabled={pending||!items.length} onChange={e=>setInstallation(e.target.value)}>{!items.length&&<option value={installation}>{tr('已保存的安装','Saved installation')}</option>}{items.map(i=><option value={i.id} key={i.id}>{i.path}</option>)}</Select></Field>}
      </>}
      {error&&<Notice tone="danger">{error}</Notice>}
      <Field label={tr('项目目录','Project directory')} required hint={tr('目标设备上的绝对路径。使用该设备的 Agent 账号和模型配置。','Absolute path on the target device. Uses that device’s Agent account and model configuration.')}><div className="edge-agent-directory-path"><Input value={project} maxLength={4096} disabled={pending} placeholder="/path/to/project" onChange={e=>setProject(e.target.value)}/><Button disabled={pending||!edge} onClick={()=>setBrowsing(true)}>{tr('浏览','Browse')}</Button></div></Field>
      <Notice>{tr('仅登记已有 Agent；新建或恢复会话时按需启动，不影响桌面进程。','Registers an existing Agent. Instances start on demand without taking over desktop processes.')}</Notice>
    </div>
  </Modal>{browsing&&<DirectoryBrowser edge={Number(edge)} accessID={entry?.edge_id===Number(edge)?entry.id:undefined} current={project} onClose={()=>setBrowsing(false)} onSelect={path=>{setProject(path);setBrowsing(false);}}/>}</>;
}
